spring:
  aop:
    auto: true # Add @EnableAspectJAutoProxy.
    proxy-target-class: true # Whether subclass-based (CGLIB) proxies are to be created (true), as opposed to standard Java interface-based proxies (false).
# IDENTITY (ContextIdApplicationContextInitializer)
  application: 
    name: BTSE Engine Trader # Application name.
  output:
    ansi:
      enabled: detect
  main:
    banner-mode: console # Mode used to display the banner when the application runs.
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:./data/demo
    username: cast
    password: Aa12345678
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /private-mgmt/h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  banner: # BANNER
    charset: UTF-8 # Banner file encoding.
#    location: classpath:banner.txt # Banner text resource location.
    image:
      location: classpath:5308460430_05413110cf_o.jpg # Banner image file location (jpg or png can also be used).
      width: 256 # Width of the banner image in chars.
      height: # Height of the banner image in chars (default based on image height).
      margin: 2 # Left hand image margin in chars.
      invert: false # Whether images should be inverted for dark terminal themes.

#    properties:
#      hibernate.hbm2ddl.import_files: import_active_users.sql,import_inactive_users.sql
# default: schema.sql
#    defer-datasource-initialization: true
#  sql:
#    init.data-locations: import_active_users.sql,import_inactive_users.sql
# default: data.sql
#    mode: never
#logging:
#  config: classpath:log4j2.yml

server:
  port: 9527
btse:
  matchEngineConfigObjectMap:
    SPOT:
      - matchServerType: TRADE
        serverConnectionString: btse01:17000;btse03:17000
      - matchServerType: QUERY
        serverConnectionString: btse01:17100;btse03:17100
    FUTURES:
      - matchServerType: TRADE
        serverConnectionString: btse02:18000;btse04:18000;btse06:18000;btse08:18000;
      - matchServerType: QUERY
        serverConnectionString: btse02:18100;btse04:18100;btse06:18100;btse08:18100;
    TRADESERVER:
      - matchServerType: TRADEFILLS
        serverConnectionString: trade01:10050;trade02:10050;
  threadMgmt:
    QUERY:
      minThread: 1
      maxThread: 2
    TRADE:
      minThread: 1
      maxThread: 8