spring:
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:./data/demo
    username: cast
    password: Aa12345678
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /private-mgmt/h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate.hbm2ddl.import_files: import_active_users.sql,import_inactive_users.sql
# default: schema.sql
#    defer-datasource-initialization: true
#  sql:
#    init.data-locations: import_active_users.sql,import_inactive_users.sql
# default: data.sql
#    mode: never